import 'package:flutter/material.dart';

enum AppIcons {
  home,
  settings,
  close,
  close_large,
  collection,
  download,
  expand,
  fullscreen,
  fullscreen_exit,
  info,
  menu,
  next_large,
  north,
  prev,
  reset_location,
  search,
  share_android,
  share_ios,
  timeline,
  wallpaper,
  keyboard,
  mic,
  zoom_in,
  zoom_out;

  static final Map<AppIcons, IconData> iconMap = {
    home: Icons.home,
    settings: Icons.settings,
    prev: Icons.arrow_back,
    close: Icons.close,
    menu: Icons.menu,
    search: Icons.search,
    info: Icons.info,
    close_large: Icons.close,
    collection: Icons.grid_on_outlined,
    download: Icons.download,
    expand: Icons.expand_more,
    fullscreen: Icons.fullscreen,
    fullscreen_exit: Icons.fullscreen_exit,
    next_large: Icons.arrow_back,
    north: Icons.north,
    reset_location: Icons.north,
    share_android: Icons.share,
    share_ios: Icons.ios_share,
    timeline: Icons.show_chart,
    wallpaper: Icons.grid_on_outlined,
    zoom_in: Icons.zoom_in,
    zoom_out: Icons.zoom_out,
    keyboard: Icons.keyboard,
    mic: Icons.mic,
  };

  static IconData icon(AppIcons icon) => iconMap[icon]!;
}
